<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Edit.aspx.cs" Inherits="esuspomogiv2.Admin.Edit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">





    <asp:GridView ID="GridView1" runat="server" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">

    </asp:GridView>

</asp:Content>
